/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author ASUS
 */
public class BayarPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BayarPage.class.getName());

    /**
     * Creates new form BayarPage
     */
    private String nama;
    private String email;
    private String noTelepon;
    private String tanggal;
    private String jamSewa;
    private String durasi;
    private String ruangan;

    public BayarPage() {
        initComponents();
        
        btnHistory.setContentAreaFilled(false);
        btnHistory.setBorderPainted(false);
        btnHistory.setFocusPainted(false);
        btnHistory.setOpaque(false);
        
        btnHome.setContentAreaFilled(false);
        btnHome.setBorderPainted(false);
        btnHome.setFocusPainted(false);
        btnHome.setOpaque(false);
        
        btnKonfirmasi.setContentAreaFilled(false);
        btnKonfirmasi.setBorderPainted(false);
        btnKonfirmasi.setFocusPainted(false);
        btnKonfirmasi.setOpaque(false);
    }

    public BayarPage(String nama, String email,
                 String noTelepon, String tanggal,
                 String jamSewa, String durasi,
                 String ruangan) {
        initComponents();

        this.nama = nama;
        this.email = email;
        this.noTelepon = noTelepon;
        this.tanggal = tanggal;
        this.jamSewa = jamSewa;
        this.durasi = durasi;
        this.ruangan = ruangan;

        btnHistory.setContentAreaFilled(false);
        btnHistory.setBorderPainted(false);
        btnHistory.setFocusPainted(false);
        btnHistory.setOpaque(false);

        btnHome.setContentAreaFilled(false);
        btnHome.setBorderPainted(false);
        btnHome.setFocusPainted(false);
        btnHome.setOpaque(false);
        
        btnKonfirmasi.setContentAreaFilled(false);
        btnKonfirmasi.setBorderPainted(false);
        btnKonfirmasi.setFocusPainted(false);
        btnKonfirmasi.setOpaque(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHome = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnKonfirmasi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.addActionListener(this::btnHomeActionPerformed);
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 80, 70));

        btnHistory.addActionListener(this::btnHistoryActionPerformed);
        getContentPane().add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 470, 80, 70));

        btnKonfirmasi.addActionListener(this::btnKonfirmasiActionPerformed);
        getContentPane().add(btnKonfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 100, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BayarPage.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        System.out.println("Bayar diklik");
        new HistoryPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        System.out.println("Bayar diklik");
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiActionPerformed
        // TODO add your handling code here:
        try {
        Connection conn = Koneksi.getConnection();

        // =========================
        // 1. Simpan ke tabel penyewa
        // =========================
        String sqlPenyewa =
                "INSERT INTO penyewa(nama,email,no_telp) VALUES(?,?,?)";

        PreparedStatement pstPenyewa =
                conn.prepareStatement(sqlPenyewa,
                        PreparedStatement.RETURN_GENERATED_KEYS);

        pstPenyewa.setString(1, nama);
        pstPenyewa.setString(2, email);
        pstPenyewa.setString(3, noTelepon);

        pstPenyewa.executeUpdate();

        ResultSet rsPenyewa = pstPenyewa.getGeneratedKeys();
        int idPenyewa = 0;

        if (rsPenyewa.next()) {
            idPenyewa = rsPenyewa.getInt(1);
        }

        // =========================
        // 2. Cari id_ruangan
        // =========================
        String sqlRuangan =
                "SELECT id_ruangan, harga_per_jam "
                + "FROM ruangan WHERE nama_ruangan=?";

        PreparedStatement pstRuangan =
                conn.prepareStatement(sqlRuangan);

        pstRuangan.setString(1, ruangan);

        ResultSet rsRuangan = pstRuangan.executeQuery();

        int idRuangan = 0;
        int hargaPerJam = 0;

        if (rsRuangan.next()) {
            idRuangan = rsRuangan.getInt("id_ruangan");
            hargaPerJam = rsRuangan.getInt("harga_per_jam");
        }
        
        int lama = Integer.parseInt(
            durasi.replace(" Jam", "")
        );

        int totalBayar = lama * hargaPerJam;
        
                String sqlBooking =
                "INSERT INTO booking "
                + "(id_penyewa,id_ruangan,"
                + "tanggal_sewa,jam_mulai,"
                + "jam_selesai,durasi,"
                + "total_bayar,status_booking)"
                + " VALUES(?,?,?,?,?,?,?,?)";

        PreparedStatement pstBooking =
                conn.prepareStatement(sqlBooking,
                        PreparedStatement.RETURN_GENERATED_KEYS);

        DateTimeFormatter inputTanggal =
        DateTimeFormatter.ofPattern("dd-MM-yyyy");

LocalDate tgl =
        LocalDate.parse(tanggal, inputTanggal);

String tanggalDB = tgl.toString();

LocalTime jam = LocalTime.parse(jamSewa);
LocalTime jamSelesai = jam.plusHours(lama);
String jamSelesaiDB = jamSelesai.toString();

String jamDB = jam.toString();

        pstBooking.setInt(1, idPenyewa);
        pstBooking.setInt(2, idRuangan);
        pstBooking.setString(3, tanggalDB);
        pstBooking.setString(4, jamDB);
        pstBooking.setString(5, jamSelesaiDB);
        pstBooking.setInt(6, lama);
        pstBooking.setInt(7, totalBayar);
        pstBooking.setString(8, "Menunggu Konfirmasi");

        pstBooking.executeUpdate();

        ResultSet rsBooking =
                pstBooking.getGeneratedKeys();

        int idBooking = 0;

        if (rsBooking.next()) {
            idBooking = rsBooking.getInt(1);
        }
        
                String sqlBayar =
                "INSERT INTO pembayaran "
                + "(id_booking,"
                + "metode_pembayaran,"
                + "tanggal_bayar,"
                + "status_pembayaran)"
                + " VALUES(?,?,NOW(),?)";

        PreparedStatement pstBayar =
                conn.prepareStatement(sqlBayar);

        pstBayar.setInt(1, idBooking);
        pstBayar.setString(2, "Transfer");
        pstBayar.setString(3, "Menunggu");

        pstBayar.executeUpdate();
        
                JOptionPane.showMessageDialog(this,
                "Pesanan berhasil dikirim!\n"
                + "Silakan tunggu konfirmasi admin.");

        new HistoryPage().setVisible(false);
        this.dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Gagal menyimpan data : "
                        + e.getMessage());
    }
        
        System.out.println("Konfrimasi diklik");

    }//GEN-LAST:event_btnKonfirmasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BayarPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnKonfirmasi;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
