/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class DetailPesananPage extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetailPesananPage.class.getName());

    /**
     * Creates new form DetailPesananPage
     */
    public DetailPesananPage() {
        initComponents();
        
        btnHistory.setContentAreaFilled(false);
        btnHistory.setBorderPainted(false);
        btnHistory.setFocusPainted(false);
        btnHistory.setOpaque(false);
        
        btnHome.setContentAreaFilled(false);
        btnHome.setBorderPainted(false);
        btnHome.setFocusPainted(false);
        btnHome.setOpaque(false);
        
        btnKonfrimasi.setContentAreaFilled(false);
        btnKonfrimasi.setBorderPainted(false);
        btnKonfrimasi.setFocusPainted(false);
        btnKonfrimasi.setOpaque(false);
    }
    
    public DetailPesananPage(String nama, String email,
                         String noTelepon, String tanggal,
                         String jamSewa, String durasi) {
        initComponents();

        lblNama.setText(nama);
        lblEmail.setText(email);
        lblNoTelepon.setText(noTelepon);
        lblTanggal.setText(tanggal);
        lblJamSewa.setText(jamSewa);
        lblDurasi.setText(durasi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHistory = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        lblNama = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblNoTelepon = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        lblJamSewa = new javax.swing.JLabel();
        btnKonfrimasi = new javax.swing.JButton();
        lblDurasi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHistory.addActionListener(this::btnHistoryActionPerformed);
        getContentPane().add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 90, 70));

        btnHome.addActionListener(this::btnHomeActionPerformed);
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 80, 70));

        lblNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setText("Nama");
        getContentPane().add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, 30));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        lblNoTelepon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNoTelepon.setForeground(new java.awt.Color(255, 255, 255));
        lblNoTelepon.setText("No Telp");
        getContentPane().add(lblNoTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, 60));

        lblTanggal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lblTanggal.setText("Tanggal");
        getContentPane().add(lblTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, 30));

        lblJamSewa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJamSewa.setForeground(new java.awt.Color(255, 255, 255));
        lblJamSewa.setText("Jam Sewa");
        getContentPane().add(lblJamSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, 60));

        btnKonfrimasi.addActionListener(this::btnKonfrimasiActionPerformed);
        getContentPane().add(btnKonfrimasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 100, 30));

        lblDurasi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDurasi.setForeground(new java.awt.Color(255, 255, 255));
        lblDurasi.setText("jLabel2");
        getContentPane().add(lblDurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DetailPesananPage.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        System.out.println("Home diklik");
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        System.out.println("History diklik");
        new HistoryPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnKonfrimasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfrimasiActionPerformed
        System.out.println("Bayar diklik");
        new BayarPage().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnKonfrimasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DetailPesananPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnKonfrimasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDurasi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblJamSewa;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNoTelepon;
    private javax.swing.JLabel lblTanggal;
    // End of variables declaration//GEN-END:variables
}
