/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class HomePage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomePage.class.getName());

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();

        btnRENT.setContentAreaFilled(false);
        btnRENT.setBorderPainted(false);
        btnRENT.setFocusPainted(false);
        btnRENT.setOpaque(false);
        
        btnRentPage.setContentAreaFilled(false);
        btnRentPage.setBorderPainted(false);
        btnRentPage.setFocusPainted(false);
        btnRentPage.setOpaque(false);
        
        btnHistory.setContentAreaFilled(false);
        btnHistory.setBorderPainted(false);
        btnHistory.setFocusPainted(false);
        btnHistory.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRENT = new javax.swing.JButton();
        btnRentPage = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnAdminPage = new javax.swing.JButton();
        lblbw = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRENT.addActionListener(this::btnRENTActionPerformed);
        getContentPane().add(btnRENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 110, 30));

        btnRentPage.addActionListener(this::btnRentPageActionPerformed);
        getContentPane().add(btnRentPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 70, 50));

        btnHistory.addActionListener(this::btnHistoryActionPerformed);
        getContentPane().add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 90, 70));

        btnAdminPage.setText("jButton1");
        btnAdminPage.addActionListener(this::btnAdminPageActionPerformed);
        getContentPane().add(btnAdminPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblbw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomePage.jpeg"))); // NOI18N
        getContentPane().add(lblbw, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRENTActionPerformed
        // TODO add your handling code here:
       System.out.println("Klik!");

        try {
            RentPage rent = new RentPage();
            rent.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRENTActionPerformed

    private void btnRentPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentPageActionPerformed
        // TODO add your handling code here:
        System.out.println("Klik!");

        try {
            RentPage rent = new RentPage();
            rent.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRentPageActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        System.out.println("History diklik");
        new HistoryPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnAdminPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminPageActionPerformed
        // TODO add your handling code here:
        System.out.println("History diklik");
        new AdminPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomePage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminPage;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnRENT;
    private javax.swing.JButton btnRentPage;
    private javax.swing.JLabel lblbw;
    // End of variables declaration//GEN-END:variables
}
