/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class RentPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RentPage.class.getName());

    private String ruanganDipilih = "";
    /**
     * Creates new form RentPage
     */
    public RentPage() {
        initComponents();
        
        btnRoom1.setOpaque(true);
        btnRoom2.setOpaque(true);
        btnRoom3.setOpaque(true);
        btnRoom4.setOpaque(true);
        btnRoom5.setOpaque(true);
        btnRoom6.setOpaque(true);
        btnRoom7.setOpaque(true);
        btnRoom8.setOpaque(true);
        btnRoom9.setOpaque(true);
        
        btnRoom1.setContentAreaFilled(false);
        btnRoom1.setBorderPainted(false);
        btnRoom1.setFocusPainted(false);
        btnRoom1.setOpaque(false);
        
        btnRoom2.setBorderPainted(false);
        btnRoom2.setFocusPainted(false);
        btnRoom2.setOpaque(false);
        btnRoom2.setContentAreaFilled(false);
        
        btnRoom3.setContentAreaFilled(false);
        btnRoom3.setBorderPainted(false);
        btnRoom3.setFocusPainted(false);
        btnRoom3.setOpaque(false);
        
        btnRoom4.setContentAreaFilled(false);
        btnRoom4.setBorderPainted(false);
        btnRoom4.setFocusPainted(false);
        btnRoom4.setOpaque(false);
        
        btnRoom5.setContentAreaFilled(false);
        btnRoom5.setBorderPainted(false);
        btnRoom5.setFocusPainted(false);
        btnRoom5.setOpaque(false);
        
        btnRoom6.setContentAreaFilled(false);
        btnRoom6.setBorderPainted(false);
        btnRoom6.setFocusPainted(false);
        btnRoom6.setOpaque(false);
        
        btnRoom7.setContentAreaFilled(false);
        btnRoom7.setBorderPainted(false);
        btnRoom7.setFocusPainted(false);
        btnRoom7.setOpaque(false);
        
        btnRoom8.setContentAreaFilled(false);
        btnRoom8.setBorderPainted(false);
        btnRoom8.setFocusPainted(false);
        btnRoom8.setOpaque(false);
        
        btnRoom9.setContentAreaFilled(false);
        btnRoom9.setBorderPainted(false);
        btnRoom9.setFocusPainted(false);
        btnRoom9.setOpaque(false);
        
        btnHome.setContentAreaFilled(false);
        btnHome.setBorderPainted(false);
        btnHome.setFocusPainted(false);
        btnHome.setOpaque(false);
        
        btnPesan.setContentAreaFilled(false);
        btnPesan.setBorderPainted(false);
        btnPesan.setFocusPainted(false);
        btnPesan.setOpaque(false);
        
        btnHistory.setContentAreaFilled(false);
        btnHistory.setBorderPainted(false);
        btnHistory.setFocusPainted(false);
        btnHistory.setOpaque(false);
    }
    
    private void pilihRuangan(String namaRuangan, javax.swing.JButton btn) {
        resetWarna();

        ruanganDipilih = namaRuangan;

        btn.setBackground(java.awt.Color.GREEN);
        
        System.out.println("Dipilih : " + ruanganDipilih);
    }
   
    private void resetWarna() {
        btnRoom1.setBackground(java.awt.Color.WHITE);
        btnRoom2.setBackground(java.awt.Color.WHITE);
        btnRoom3.setBackground(java.awt.Color.WHITE);
        btnRoom4.setBackground(java.awt.Color.WHITE);
        btnRoom5.setBackground(java.awt.Color.WHITE);
        btnRoom6.setBackground(java.awt.Color.WHITE);
        btnRoom7.setBackground(java.awt.Color.WHITE);
        btnRoom8.setBackground(java.awt.Color.WHITE);
        btnRoom9.setBackground(java.awt.Color.WHITE);
    }

    private void resetLabel() {
        lblStatus1.setText("");
        lblStatus2.setText("");
        lblStatus3.setText("");
        lblStatus4.setText("");
        lblStatus5.setText("");
        lblStatus6.setText("");
        lblStatus7.setText("");
        lblStatus8.setText("");
        lblStatus9.setText("");
    }
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHome = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        txtNama = new javax.swing.JTextField();
        txtNama1 = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNoTelepon = new javax.swing.JTextField();
        txtJamSewa = new javax.swing.JTextField();
        btnPesan = new javax.swing.JButton();
        cmbDurasi = new javax.swing.JComboBox<>();
        btnRoom1 = new javax.swing.JButton();
        btnRoom2 = new javax.swing.JButton();
        btnRoom3 = new javax.swing.JButton();
        btnRoom4 = new javax.swing.JButton();
        btnRoom5 = new javax.swing.JButton();
        btnRoom6 = new javax.swing.JButton();
        btnRoom7 = new javax.swing.JButton();
        btnRoom8 = new javax.swing.JButton();
        btnRoom9 = new javax.swing.JButton();
        lblStatus9 = new javax.swing.JLabel();
        lblStatus8 = new javax.swing.JLabel();
        lblStatus7 = new javax.swing.JLabel();
        lblStatus6 = new javax.swing.JLabel();
        lblStatus5 = new javax.swing.JLabel();
        lblStatus4 = new javax.swing.JLabel();
        lblStatus3 = new javax.swing.JLabel();
        lblStatus2 = new javax.swing.JLabel();
        lblStatus1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.addActionListener(this::btnHomeActionPerformed);
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 80, 70));

        btnHistory.addActionListener(this::btnHistoryActionPerformed);
        getContentPane().add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 90, 70));

        txtNama.addActionListener(this::txtNamaActionPerformed);
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 160, -1));

        txtNama1.addActionListener(this::txtNama1ActionPerformed);
        getContentPane().add(txtNama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 160, -1));

        txtEmail.addActionListener(this::txtEmailActionPerformed);
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 160, -1));
        getContentPane().add(txtNoTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 160, -1));
        getContentPane().add(txtJamSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 160, -1));

        btnPesan.addActionListener(this::btnPesanActionPerformed);
        getContentPane().add(btnPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 130, 30));

        cmbDurasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Jam", "2 Jam", "3 Jam", "4 Jam", "5 Jam", "6 Jam", "7 Jam", "8 Jam", "9 Jam", "10 Jam" }));
        cmbDurasi.addActionListener(this::cmbDurasiActionPerformed);
        getContentPane().add(cmbDurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 160, -1));

        btnRoom1.setText("Room 1");
        btnRoom1.addActionListener(this::btnRoom1ActionPerformed);
        getContentPane().add(btnRoom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 100, 50));

        btnRoom2.setText("Room 2");
        btnRoom2.addActionListener(this::btnRoom2ActionPerformed);
        getContentPane().add(btnRoom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 90, 50));

        btnRoom3.setText("Room 3");
        btnRoom3.addActionListener(this::btnRoom3ActionPerformed);
        getContentPane().add(btnRoom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 100, 50));

        btnRoom4.setText("Room 4");
        btnRoom4.addActionListener(this::btnRoom4ActionPerformed);
        getContentPane().add(btnRoom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 100, 50));

        btnRoom5.setText("Room 5");
        btnRoom5.addActionListener(this::btnRoom5ActionPerformed);
        getContentPane().add(btnRoom5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 110, 50));

        btnRoom6.setText("Room 6");
        btnRoom6.addActionListener(this::btnRoom6ActionPerformed);
        getContentPane().add(btnRoom6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 100, 50));

        btnRoom7.setText("Room 7");
        btnRoom7.addActionListener(this::btnRoom7ActionPerformed);
        getContentPane().add(btnRoom7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 100, 60));

        btnRoom8.setText("Room 8");
        btnRoom8.addActionListener(this::btnRoom8ActionPerformed);
        getContentPane().add(btnRoom8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 110, 60));

        btnRoom9.setText("Room 9");
        btnRoom9.addActionListener(this::btnRoom9ActionPerformed);
        getContentPane().add(btnRoom9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 100, 60));
        getContentPane().add(lblStatus9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, 70, 30));
        getContentPane().add(lblStatus8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, -1, -1));
        getContentPane().add(lblStatus7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));
        getContentPane().add(lblStatus6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, -1, -1));
        getContentPane().add(lblStatus5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, -1, -1));
        getContentPane().add(lblStatus4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));
        getContentPane().add(lblStatus3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, -1, -1));
        getContentPane().add(lblStatus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, -1, -1));
        getContentPane().add(lblStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RentPage.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        System.out.println("History diklik");
        new HistoryPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        System.out.println("Home diklik");
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtNama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNama1ActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
        String nama = txtNama.getText();
        String email = txtEmail.getText();
        String noTelepon = txtNoTelepon.getText();
        String jamSewa = txtJamSewa.getText();
        String durasi = cmbDurasi.getSelectedItem().toString();
        
        String tanggal = "";
            if (jDateChooser1.getDate() != null) {
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MM-yyyy");
                tanggal = sdf.format(jDateChooser1.getDate());
            } else {
                JOptionPane.showMessageDialog(this, "Silakan pilih tanggal terlebih dahulu!");
                return;
            }
            
            if (ruanganDipilih == null || ruanganDipilih.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Silakan pilih ruangan terlebih dahulu!");
                return; 
            }

        DetailPesananPage detail = new DetailPesananPage(
                nama,
                email,
                noTelepon,
                tanggal,
                jamSewa,
                durasi,
                ruanganDipilih
        );
       
        detail.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPesanActionPerformed

    private void cmbDurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDurasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDurasiActionPerformed

    private void btnRoom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoom1ActionPerformed
        // TODO add your handling code here:
        resetLabel();
        pilihRuangan("Room 1", btnRoom1);
        ruanganDipilih = "Room 1";
        lblStatus1.setText("✔");
    }//GEN-LAST:event_btnRoom1ActionPerformed

    private void btnRoom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoom2ActionPerformed
        // TODO add your handling code here:
        resetLabel();
        pilihRuangan("Room 2", btnRoom2);
        ruanganDipilih = "Room 2";
        lblStatus2.setText("✔");
    }//GEN-LAST:event_btnRoom2ActionPerformed

    private void btnRoom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoom3ActionPerformed
        // TODO add your handling code here:
        resetLabel();
        pilihRuangan("Room 3", btnRoom3);
        ruanganDipilih = "Room 3";
        lblStatus3.setText("✔");
    }//GEN-LAST:event_btnRoom3ActionPerformed

    private void btnRoom4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoom4ActionPerformed
        // TODO add your handling code here:
        resetLabel();
        pilihRuangan("Room 4", btnRoom4);
        ruanganDipilih = "Room 4";
        lblStatus4.setText("✔");
    }//GEN-LAST:event_btnRoom4ActionPerformed

    private void btnRoom5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoom5ActionPerformed
        // TODO add your handling code here:
        resetLabel();
        pilihRuangan("Room 5", btnRoom5);
        ruanganDipilih = "Room 5";
        lblStatus5.setText("✔");
    }//GEN-LAST:event_btnRoom5ActionPerformed

    private void btnRoom6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoom6ActionPerformed
        // TODO add your handling code here:
        resetLabel();
        pilihRuangan("Room 6", btnRoom6);
        ruanganDipilih = "Room 6";
        lblStatus6.setText("✔");
    }//GEN-LAST:event_btnRoom6ActionPerformed

    private void btnRoom7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoom7ActionPerformed
        // TODO add your handling code here:
        resetLabel();
        pilihRuangan("Room 7", btnRoom7);
        ruanganDipilih = "Room 7";
        lblStatus7.setText("✔");
    }//GEN-LAST:event_btnRoom7ActionPerformed

    private void btnRoom8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoom8ActionPerformed
        // TODO add your handling code here:
        resetLabel();
        pilihRuangan("Room 8", btnRoom8);
        ruanganDipilih = "Room 8";
        lblStatus8.setText("✔");
    }//GEN-LAST:event_btnRoom8ActionPerformed

    private void btnRoom9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoom9ActionPerformed
        // TODO add your handling code here:
        resetLabel();
        pilihRuangan("Room 9", btnRoom9);
        ruanganDipilih = "Room 9";
        lblStatus9.setText("✔");
    }//GEN-LAST:event_btnRoom9ActionPerformed
                 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RentPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnRoom1;
    private javax.swing.JButton btnRoom2;
    private javax.swing.JButton btnRoom3;
    private javax.swing.JButton btnRoom4;
    private javax.swing.JButton btnRoom5;
    private javax.swing.JButton btnRoom6;
    private javax.swing.JButton btnRoom7;
    private javax.swing.JButton btnRoom8;
    private javax.swing.JButton btnRoom9;
    private javax.swing.JComboBox<String> cmbDurasi;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblStatus1;
    private javax.swing.JLabel lblStatus2;
    private javax.swing.JLabel lblStatus3;
    private javax.swing.JLabel lblStatus4;
    private javax.swing.JLabel lblStatus5;
    private javax.swing.JLabel lblStatus6;
    private javax.swing.JLabel lblStatus7;
    private javax.swing.JLabel lblStatus8;
    private javax.swing.JLabel lblStatus9;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtJamSewa;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNama1;
    private javax.swing.JTextField txtNoTelepon;
    // End of variables declaration//GEN-END:variables
}
