/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class RentPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RentPage.class.getName());

    /**
     * Creates new form RentPage
     */
    public RentPage() {
        initComponents();
        
        btnHome.setContentAreaFilled(false);
        btnHome.setBorderPainted(false);
        btnHome.setFocusPainted(false);
        btnHome.setOpaque(false);
        
        btnPesan.setContentAreaFilled(false);
        btnPesan.setBorderPainted(false);
        btnPesan.setFocusPainted(false);
        btnPesan.setOpaque(false);
        
        btnHistory.setContentAreaFilled(false);
        btnHistory.setBorderPainted(false);
        btnHistory.setFocusPainted(false);
        btnHistory.setOpaque(false);
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHome = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        txtNama = new javax.swing.JTextField();
        txtNama1 = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNoTelepon = new javax.swing.JTextField();
        txtJamSewa = new javax.swing.JTextField();
        btnPesan = new javax.swing.JButton();
        cmbDurasi = new javax.swing.JComboBox<>();
        txtTanggal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.addActionListener(this::btnHomeActionPerformed);
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 80, 70));

        btnHistory.addActionListener(this::btnHistoryActionPerformed);
        getContentPane().add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 90, 70));

        txtNama.addActionListener(this::txtNamaActionPerformed);
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 160, -1));

        txtNama1.addActionListener(this::txtNama1ActionPerformed);
        getContentPane().add(txtNama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 160, -1));

        txtEmail.addActionListener(this::txtEmailActionPerformed);
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 160, -1));
        getContentPane().add(txtNoTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 160, -1));
        getContentPane().add(txtJamSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 160, -1));

        btnPesan.addActionListener(this::btnPesanActionPerformed);
        getContentPane().add(btnPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 130, 30));

        cmbDurasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Jam", "2 Jam", "3 Jam", "4 Jam", "5 Jam", "6 Jam", "7 Jam", "8 Jam", "9 Jam", "10 Jam" }));
        cmbDurasi.addActionListener(this::cmbDurasiActionPerformed);
        getContentPane().add(cmbDurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 160, -1));

        txtTanggal.addActionListener(this::txtTanggalActionPerformed);
        getContentPane().add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RentPage.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        System.out.println("History diklik");
        new HistoryPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        System.out.println("Home diklik");
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtNama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNama1ActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
        String nama = txtNama.getText();
        String email = txtEmail.getText();
        String noTelepon = txtNoTelepon.getText();
        String tanggal = txtTanggal.getText();
        String jamSewa = txtJamSewa.getText();
        String durasi = cmbDurasi.getSelectedItem().toString();

        DetailPesananPage detail = new DetailPesananPage(
                nama,
                email,
                noTelepon,
                tanggal,
                jamSewa,
                durasi
        );

        detail.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPesanActionPerformed

    private void cmbDurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDurasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDurasiActionPerformed

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RentPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPesan;
    private javax.swing.JComboBox<String> cmbDurasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtJamSewa;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNama1;
    private javax.swing.JTextField txtNoTelepon;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
